### ISSUE TITLE
Problem with connecting to the Google MQTT bridge

### ISSUE THREAD

**Issue by KlippRid** [MicrochipTech/gcp-iot-core-examples#3]
Hi,
I'm having trouble connecting my device with IoT Core using mqtt, getting the following error codes:

INFO:root:on_connect: Connection Refused: not authorised.
INFO:root:on_disconnect: 5: The connection was refused.

I have successfully run at_pubkey.py and at_token.py, so I know I am communicating correctly with the ATECC608A chip. I suspect it is how I setup my device on IoT Core when registering the public key. 

1. Is it correct to use the key generated by at_pubkey.py as registered public key on IoT core?

2. Where is the extra data (see below) when producing a public key coming from? "bytearray.fromhex('3059301306072A8648CE3D020106082A8648CE3D03010703420004')" in 
[https://github.com/MicrochipTech/gcp-iot-core-examples/blob/938321f643e737bbe98b3737ec08ae1aa7411d4e/boards/raspi/at_pubkey.py#L23](url)

3. Followup question from 2., what does those extra bytes do? is it a generic header?

Thankful for any support/
Astrid

**Comment by bryan-hunt** [comment]
Using the results from at_pubkey.py and at_token.py have you verified the token? You can use the pyjwt module or you can use the debugger at https://jwt.io/ (make sure to select ES256) to verify the token is valid.

I would check a couple of things:

1) Check the device in the registry to verify that communication is allowed for the device, a key is assigned, that key matches the public key, and that it doesn't have expiration set that has expired
2) Check that the project_id and cloud_region are correct. These default to values that might not work - project_id will by default pull from your environment variables so if you have multiple GCP projects it might be using the wrong one.
3) Check that the registry is allowed to publish (I don't know what happens if the registry itself does not have permissions to the pubsub topic).

To answer the questions specifically:

1. Yes it would be the the value you use when you create your device. However you can add I believe up to 3 keys per device - so you can view the device and add the key if it's not there.
2. This is the x509 (asn1) information. This is static information that provides information about the public key. One could generate this dynamically by passing the raw public key to cryptography and having it generate the pem but the result is significantly more code for the same result
3. It provides all the meta data required to parse the public key:

```
$ openssl pkey -in pubkey.pem -text -noout -pubin
Public-Key: (256 bit)
pub:
    04:8b:1a:3b:e4:a0:6c:d4:b3:7e:7e:8c:43:86:b7:
    33:e5:bd:fa:35:f4:51:8d:1c:e0:3a:07:85:b9:e1:
    0b:20:e3:37:f3:3d:73:db:4e:bc:59:4c:ae:1e:c5:
    2c:79:d4:11:d8:3f:6d:d6:be:e0:ef:bc:2f:70:7f:
    29:b4:fb:29:d9
ASN1 OID: prime256v1
NIST CURVE: P-256
```
The only additional thing you will notice is the leading 0x04 added to the public key bytes. This indicates the public key is in the uncompressed format (this is the only format anybody uses and the only format the device library supports).

**Comment by KlippRid** [comment]
Thanks for the quick reply! Now it is up and running, it was actually a mismatch in device_id that I myself introduced. But great to get a better understanding on the generation of the public key, really appreciate it.
